apiVersion: v2
name: tekton-pipeline
description: A Weaveworks Helm chart for the Tekton Pipeline Profile
type: application
version: 0.0.3
dependencies:
  - name: tekton-pipeline
    version: "0.29"
    repository: "https://cdfoundation.github.io/tekton-helm-chart/"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://cdfoundation.github.io/tekton-helm-chart

keywords:
- tekton
- tekton-pipelines
- cicd

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": tekton-piepline
  "weave.works/category": CICD
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://cdfoundation.github.io/tekton-helm-chart
    - name: Upstream Project
      url: https://github.com/tektoncd/pipeline
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"
