apiVersion: v2
name: loki
description: A Weaveworks Helm chart for the Loki Profile
type: application
version: 0.0.3
dependencies:
  - name: loki
    version: "3.0.7"
    repository: "https://grafana.github.io/helm-charts"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://grafana.github.io/helm-charts

keywords:
- loki
- observability
- logging

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": loki
  "weave.works/category": observability
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://grafana.github.io/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/loki/blob/main/production/helm/loki
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"
